SiO/calapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from . import views

urlpatterns = [
	url(r'^calendar/event/get/(?P<start>.+)/(?P<end>.+)/', views.event_get),
	url(r'^calendar/event/setsync/', views.event_setsync),
	url(r'^calendar/event/delete/', views.event_delete),
	url(r'^calendar/event/addedit/', views.event_add_edit),
	url(r'^calendar/', views.calendar.as_view(), name='calendar'),

]

SiO/session_security/urls.py
try:
    from django.conf.urls import url
except ImportError:
    from django.conf.urls.defaults import url

from .views import PingView

urlpatterns = [
    url(
        'ping/$',
        PingView.as_view(),
        name='session_security_ping',
    )
]

SiO/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin

from SiO.CoAdmin import views as admin_auth_views
from SiO.member import views as member_views
from SiO.core import views as core_views
from SiO.calapp import views as events_views
from SiO.chart import views as chart_views

# from dedal.site import site as dedal_site

# TODO: Herifra blir metodene fra hver app dirigert via URL
# TODO: URL: rekkefølgen på SiO må være øverst slik at de vises i nettleser
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', core_views.home, name='home'),
    url(r'', include('SiO.core.urls')),
    url(r'', include('SiO.member.urls')),
    url(r'', include('SiO.CoAdmin.urls')),
    url(r'', include('SiO.calapp.urls')),
    url(r'', include('SiO.chart.urls')),
    url(r'', include('SiO.post.urls')),
    url(r'^login', auth_views.login, {'template_name': 'core/cover.html'},
        name='login'),
    url(r'^logout', auth_views.logout, {'next_page': '/'}, name='logout'),
    # url(r'^signup/$', admin_auth_views.signup, name='signup'),
    url(r'session_security/', include('session_security.urls')),
    # url(r'^membersignup/$', member_views.membersignup, name='membersignup'),
    url(r'^(?P<username>[^/]+)/$', core_views.profile, name='profile'),
    # url(r'', include('SiO.calapp.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
    # url(r'^', include(dedal_site.urls)),
    # url(r'^calapp/$', events_views.calapp, name='calapp'),

    # url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    # url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    # url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     auth_views.password_reset_confirm, name='password_reset_confirm'),
    # url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'SiO administration'

SiO/CoAdmin/models.py
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser
from SiO.member.models import Association


class Administrator(AbstractUser):
    union_position = models.CharField(max_length=100)
    email = models.CharField(max_length=255, blank=True, unique=True)
    association = models.ForeignKey(Association)

    class Meta:
        db_table = 'Administrator'

    def __str__(self):
        return self.username

    def __unicode__(self):
        return self.username


class Event(models.Model):
    name = models.CharField(max_length=50)
    location = models.CharField(max_length=100)
    start = models.DateTimeField(blank=False)
    end = models.DateTimeField(blank=False)
    allday = models.BooleanField()
    description = models.TextField(max_length=200)
    synced = models.BooleanField(default=False)
    gid = models.CharField(default='', max_length=100)
    association = models.ForeignKey(Association)

    class Meta:
        db_table = 'Event'

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(Administrator)

    class Meta:
        db_table = 'Profile'

    def __str__(self):
        return self.user.username

    def get_screen_name(self):
        try:
            if self.user.get_full_name():
                return self.user.get_full_name()
            else:
                return self.user.username
        except:
            return self.user.username

    def get_association_name(self):
        try:
            if self.user.association:
                return self.user.association
            else:
                return self.user.username
        except:
            return self.user.username


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


post_save.connect(create_user_profile, sender=Administrator)
post_save.connect(save_user_profile, sender=Administrator)

SiO/calapp/models.py
from django.db import models

# Create your models here.

SiO/calapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.generic import ListView

from datetime import datetime

from SiO.CoAdmin.models import Event, Administrator
from SiO.CoAdmin.models import Association


class calendar(ListView):

    model = Event
    template_name = 'calapp/calendar.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(calendar, self).dispatch(request, *args, **kwargs)


@login_required
def event_get(request, start, end):
    res = {'success': False}
    try:
        datetime.strptime(start, '%Y-%m-%dT%H:%M:%S.%fZ')
        datetime.strptime(end, '%Y-%m-%dT%H:%M:%S.%fZ')
    except ValueError:
        res['message'] = \
            'Invalid params: ISO format start end dates expected'
        return JsonResponse(res)
    result = Event.objects.filter(
        association=request.user.association,
        start__range=(start, end)).order_by('start').values()

    res['data'] = list(result)
    res['success'] = True
    return JsonResponse(res)


def paramMissing(POST, param, res):
    if param not in POST:
        res['message'] = param + ' param missing'
        return True
    return False


@login_required
def event_delete(request):
    if request.method == 'POST':
        res = {'success': False}

        if paramMissing(request.POST, 'eid', res):
            return JsonResponse(res)

        eid = request.POST['eid']
        Event.objects.filter(id=eid).delete()

        res['success'] = True
        res['message'] = 'deleted'
        res['eid'] = eid
        return JsonResponse(res)
    else:
        raise Http404


@login_required
def event_add_edit(request):
    if request.method == 'POST':
        res = {'success': False}

        gid = request.POST.get('gid', '')
        action = request.POST['action']
        name = request.POST['name']
        location = request.POST['location']
        start = request.POST['start']
        end = request.POST['end']
        allday = request.POST['allday'] == 'true'
        description = request.POST['description']
        synced = request.POST['synced'] == 'true'
        association = Administrator.objects.filter(id=request.user.id).values('association__asoc_name')
        asoc = Association.objects.get(asoc_name=association)

        if action == 'add':
            Event.objects.create(
                name=name,
                location=location,
                start=start,
                end=end,
                allday=allday,
                description=description,
                synced=synced,
                gid=gid,
                association=asoc
            )

            res['success'] = True
            res['message'] = 'added'
            eid = Event.objects.latest('id').id
            res['eid'] = eid
            res['data'] = Event.objects.values().get(id=eid)

        elif action == 'edit':

            if paramMissing(request.POST, 'eid', res):
                return JsonResponse(res)

            eid = request.POST['eid']
            event = Event.objects.get(id=eid)
            event.name = name
            event.location = location
            event.start = start
            event.end = end
            event.allday = allday
            event.description = description
            event.synced = synced
            event.save()

            res['success'] = True
            res['message'] = 'edited'
            res['eid'] = eid
            res['data'] = Event.objects.values().get(id=eid)

        return JsonResponse(res)
    else:
        raise Http404


@login_required
def event_setsync(request):
    if request.method == 'POST':
        res = {'success': False}

        if paramMissing(request.POST, 'eid', res) \
                or paramMissing(request.POST, 'gid', res):
            return JsonResponse(res)

        eid = request.POST['eid']
        gid = request.POST['gid']

        event = Event.objects.get(id=eid)
        event.synced = True
        event.gid = gid
        event.save()

        res['success'] = True
        res['message'] = 'sync set'
        res['eid'] = eid
        res['gid'] = gid
        return JsonResponse(res)
    else:
        raise Http404

SiO/calapp/templates/calapp/calendar (copy).html
{% load staticfiles %}
<html>

<head>
    <title>Calendar</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css">
    
<!--
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,500" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/mobile.css' %}">
    <script src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
    
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        var today = new Date();
        var csrf = '{{csrf_token}}';
    </script>
-->

</head>

<body>
<!--
    <div class="form-div" id="form-add-event">
        <form onsubmit="return newevent(event)" name="add-event">
            {% csrf_token %}
        <input type="hidden" name="type" id="id_type" value="add">
        <input type="hidden" name="eid"  id="id_eid" value=""> 
            <ul>
                <li class="form-li">
                    <span class="form-top">Thursday, 13 October 2016</span>
                </li>
                <li class="form-li">
                    <span class="input-field">
                        <input id="id_name" maxlength="50" name="name" placeholder="Event Name" type="text" style='text-transform:capitalize' required>
                    </span>
                </li>
                <li class="form-li">
                    <span class="input-field">
                        <input id="id_location" maxlength="50" name="location" placeholder="Location" type="text"  style='text-transform:capitalize' required>
                    </span>
                </li>
                <li class="form-li">
                    <span class="input-name">Starts</span>
                    <span class="input-field datetime-field">
                        <input id="add-event-sdate" name="start_date" type="date" ><input id="add-event-stime" name="start_time" type="time" required>
                    </span>
                </li>
                <li class="form-li">
                    <span class="input-name">Ends</span>
                    <span class="input-field datetime-field">
                        <input id="add-event-edate" name="end_date" type="date" ><input id="add-event-etime" name="end_time" type="time" required>
                    </span>
                </li>
                <li class="form-li">
                    <input id="id_allday" type="checkbox" name="allday">
                    <label for="id_allday" class="input-name"> All Day</label>
                </li>
                <li class="form-li">
                    <textarea id="id_desc" name="description" placeholder="Description"></textarea>
                </li>

                <div class="btn-div">
                    <input class="btn btn-cancel" type="button" value="Cancel">
                    <input class="btn btn-right" type="submit" value="Save">
                </div>
            </ul>
        </form>
    </div>
    <div class="form-div" id="form-show-event">
        <form>
            <ul>
                <li class="form-li">
                    <span class="form-top" id="form-show-name">Event Name</span>
                </li>
                <li class="form-li">
                    <p class="detail-label">Where</p>
                    <p id="form-show-location" class="detail-info"></p>
                </li>
                <li class="form-li">
                    <p class="detail-label">When</p>
                    <p id="form-show-date" class="detail-info"></p>
                </li>
                <li class="form-li">
                    <p class="detail-label">Description</p>
                    <p id="form-show-desc" class="detail-info"></p>
                </li>
                <div class="btn-div">
                    <input class="btn" id="btn-edit" type="button" value="Edit">
                    <input class="btn btn-right" id="btn-delete" type="button" value="Delete">
                </div>
            </ul>
        </form>
    </div>

    <div id="container">
        <div id="side-bar">
            <div id="top-side"> <span id="menu-bars"><i class="fa fa-bars" ></i></span></div>
            <div id="thumb">
              <div style="padding-left:10px">
                <span class="month"><script> document.write(today.toLocaleDateString("en-us",{month:"long"})) </script></span>
                <span class="year"><script> document.write(today.getFullYear()) </script></span>
              </div>
                <table id="cal-th-grid">
                    <tr class="week-days-th">
                        <th>Su</th>
                        <th>Mo</th>
                        <th>Tu</th>
                        <th class="selected">We</th>
                        <th>Th</th>
                        <th>Fr</th>
                        <th>Sa</th>
                    </tr>
                    <tr class="week-row-th">
                        <td class="day-cel-th not-present"></td>
                        <td class="day-cell-th not-present"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                    </tr>
                    <tr class="week-row-th">
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                    </tr>
                    <tr class="week-row-th">
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                    </tr>
                    <tr class="week-row-th">
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                    </tr>
                    <tr class="week-row-th">
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                        <td class="day-cell-th"></td>
                    </tr>
                </table>

            </div>          

            <div id="time-now">
                <span class="now" id="hr">05</span>:<span class="now" id="min">00</span>
                <em id="ampm">pm</em>

            </div>
            <div id="upcoming-events"></div>
            <div class="weather"><span>Weather</span>
                <div id="weather-details">
                    
                    <div id="w-icon">
                        <div id="ico"></div>
                        <div id="desc"></div>
                    </div>
                    <div id="max-temp"></div>
                    <div id="min-temp"></div>
                </div>
            </div>
        </div>
        <div id="content">
            <div id="top-bar">
                <div id="authorize-div" style="display: none">
                <span>Authorize access to Google Calendar API</span>
                Button for the user to click to initiate auth sequence 
                <button id="authorize-button" onclick="handleAuthClick(event)">Authorize</button>
            </div>      
            <span id="curr-month">
                    <span id="month-up">
                        <i class="fa fa-chevron-up"></i>
                    </span>
                <span id="month-dn">
                        <i class="fa fa-chevron-down"></i>
                    </span>
                <span class="month">{{ curr_month }}</span>
                <span class="year">{{ curr_year }}</span>
                </span>
                <span id="icon">
                    <span onclick="handleAuthClick(event)" id="icon-sync">
                        <i class="fa fa-refresh"></i>
                    </span>
                    <i class="fa fa-gear"></i>
                </span>
            </div>
            <div id="days-of-week">
                <table id="calendar-grid">
                    <tbody>
                        <tr class="week-days">
                            <th>Sunday</th>
                            <th>Monday</th>
                            <th>Tuesday</th>
                            <th class="selected">Wednesday</th>
                            <th>Thurday</th>
                            <th>Friday</th>
                            <th>Saturday</th>
                        </tr>
                        <tr class="week-row">
                            <td class="day-cell not-present"></td>
                            <td class="day-cell not-present">knsvnvs</td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                        </tr>
                        <tr class="week-row">
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                        </tr>
                        <tr class="week-row">
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                        </tr>
                        <tr class="week-row">
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                        </tr>
                        <tr class="week-row">
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                            <td class="day-cell"></td>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
    <script src="{% static 'js/sync.js' %}"></script>
    <script src="https://apis.google.com/js/client.js?onload=checkAuth"></script>
    <script src="{% static 'js/main.js' %}"></script>
-->
    <p>Hi! -_*</p>
</body>

</html>